config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'



  resources :articles, only:[:index, :new, :create]
  resources :proposals, only:[:index, :new]

  get "about", to: "pages#about"
  get "proposals/plan", to: "proposals#plan"
  post "proposals/results", to: "proposals#results"
end


  #:delete
  #upgrade ..



  # get "proposals/plan", to: "proposals#plan"
  # post "proposals/results", to: "proposals#results"




  # get  "artciles", to: "articles#index"

  # get  "articles/new", to: "articles#new"
  # post  "articles", to: "articles#create"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/me_vestido/"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fa fa-heart"></i> at Me Vestido
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png", height: 50 %>
  <% end %>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
<!--   <div class="col-xs-6 col-sm-4"> -->

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "👠 Your dressing", new_article_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "💃 Outfit of the day", new_proposal_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%=link_to "🤩 Meet the team", about_path, class: "navbar-wagon-item navbar-wagon-link" %>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
            <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
            <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <%#link_to t(".sign_in", default: "Meet the Team"), about_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <% if user_signed_in? %>
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "💃 Outfit of the day", new_proposal_path, class: "main" %></li>
          <li><%= link_to "👠 Your dressing", articles_path, class: "main" %></li>
          <li><%= link_to "🤩 Meet the team", about_path, class: "main" %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out",
                  destroy_user_session_path,
                  method: :delete,
                  class: "text-center" %>
          </li>
        </ul>
      </div>
    <% else %>
      <%= link_to new_user_session_path do %>
        <button class="btn btn-success chat"> Login </button>
      <% end %>
    <% end %>
  </div>
</div>