config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'



  resources :articles, only:[:index, :new, :create]
  resources :proposals, only:[:index, :new]

  get "about", to: "pages#about"
  get "proposals/plan", to: "proposals#plan"
  post "proposals/results", to: "proposals#results"
end


  #:delete
  #upgrade ..



  # get "proposals/plan", to: "proposals#plan"
  # post "proposals/results", to: "proposals#results"




  # get  "artciles", to: "articles#index"

  # get  "articles/new", to: "articles#new"
  # post  "articles", to: "articles#create"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/proposal.rb
   # == Schema Information
#
# Table name: proposals
#
#  id         :bigint(8)        not null, primary key
#  meteo      :integer
#  usage      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#


class Proposal < ApplicationRecord
  has_many :outfits, dependent: :destroy
  has_many :articles, through: :outfits

  enum meteo: [
    :spring,
    :summer,
    :autumn,
    :winter,
  ]

  enum usage: [
    :chill,
    :work,
    :night,
    :sport,
  ]

  def image
    wearable.class.images[wearable.kind.to_sym]
  end


end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

  def index
    @proposals = Proposal.all
  end

  def new
    @proposal = Proposal.new
    @usage_list = Proposal.usages
    @meteo = Proposal.meteos
  end



  def create
    @proposal = Proposal.new(proposal_params)
    if @proposal.save
      redirect_to new_proposal_path, notice: "Proposal created"
    else
      render :new
    end
  end

  def plan
    @proposal = Proposal.new
  end

  def results
    @usage = params["usage"]
    # appel à l'api de météo pour récupérer la température en integer
    weather_instance = Weather.new(current_user.city)
        # weather_instance.save!
    @meteo = weather_instance.call
    # mapping de température avec la saison
    # @season = temp_to_meteo(@meteo.temperature)
    @season = temp_to_meteo(21.2)
    #recherche des propositions correspondantes à la saison et l'usage
    #@proposals = Proposal.all.where(meteo: season, usage: params[:proposal][:usage])
    @proposals = Proposal.all.where(meteo: @season, usage: params["usage"])

  end

private

  def temp_to_meteo(t)
    if t > 17
      "summer"
    elsif t > 12
      "spring"
    elsif t > 8
      "autumn"
    else
      "winter"
    end
  end

  def proposal_params
    params.require(:proposal).permit(:usage_id, :meteo)

    # if user_choice == :chill
    #   return proposal_chill
    #   if user_choice == :work
    #     return proposal_work
    #     if user_choice == :night
    #       if user_choice == :sport
    #       end
    #     end
    #   end
    # end


  end

end

app/views/proposals/index.html.erb
<!-- <h1>liste des proposals</h1> -->

<% @proposals.each do |proposal| %>
  <%= proposal.meteo %>
<% end %>

app/views/proposals/new.html.erb
<% content_for :background_image do %>
  background-image: linear-gradient(to right bottom, #f9e5ae, #fbeabd, #fcf0cd, #fef5dc, #fffaec);
<% end %>

  <div class="container">
    <h1 class="h2 mt++ pt mb+ text-center text-bold">
      What are you up to?
    </h1>

    <div class="proposal-wrap">
      <div class="row">
        <div class="col-xs-6 col-sm-4">
          <div class="text-center">
       <!--      <div class="proposals-title mb+ mt"> WORK 👩‍💻</div> -->
            <%= button_to "Work",
                  { controller: "proposals", action: "results", usage: "work" },
                  method: :post,
                  class: "card proposal-card-work mb+" %>
          </div>
        </div>
        <div class="col-xs-6 col-sm-4">
          <div class="text-center">
            <!-- <div class="proposals-title mb+ mt"> CHILL 🦄</div> -->
            <%= button_to "Chill",
                  { controller: "proposals", action: "results", usage: "chill" },
                  method: :post,
                  class: "card proposal-card-chill mb+" %>
          </div>
        </div>
        <div class="col-xs-6 col-sm-4">
          <div class="text-center">
            <!-- <div class="proposals-title mb+ mt"> GOING OUT ✨</div> -->
            <%= button_to "Going out",
                  { controller: "proposals", action: "results", usage: "night" },
                  method: :post,
                  class: "card proposal-card-night mb+" %>
          </div>
        </div>
        <div class="col-xs-6 col-sm-4">
          <div class="text-center">
            <!-- <div class="proposals-title mb+ mt"> SPORT 👟</div> -->
            <%= button_to "Sport",
                  { controller: "proposals", action: "results", usage: "sport" },
                  method: :post,
                  class: "card proposal-card-sport mb+" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/proposals/plan.html.erb
<%= simple_form_for @proposal, url: proposals_results_path, method: :post do |f| %>
    <%= f.input :meteo, collection: Proposal.meteos.keys,
       prompt:"Select a meteo" %>
    <%= f.input :usage, collection: Proposal.usages.keys, prompt: "Select an usage" %>
    <%= f.button :submit, "Search" %>
<% end %>

app/views/proposals/results.html.erb
<% content_for :background_image do %>
  background-image: linear-gradient(to right bottom, #f9e5ae, #fbeabd, #fcf0cd, #fef5dc, #fffaec);
<% end %>

<div class="container">
  <div class="results">
    <h2>☀️</h2>

    <h3>
      It's <strong><%= @season %></strong>, temperature will be <strong><%= @meteo.temperature %>°C</strong>
    </h3>

    <h3 class="text-center mb">
      Here is what you could wear to <strong><%= @usage %></strong>
    </h3>

    <div class="row">
      <% @proposals.each_with_index do |proposal, index| %>
        <div class="col-xs-6">
          <div class="outfit">
            <% proposal.articles.each do |article| %>
              <div class="background"
                   style="background-image: radial-gradient(closest-side, <%= article.color.hex %>, <%= article.color.hex %>, <%= article.color.hex %>, <%= article.color.hex %>, <%= article.color.hex %>, <%= article.color.hex %>, white);">
                <%= image_tag article.image, alt: "Article", height: 250, width: 167 %>
                 <div class="card-info">
                  <div class="infos">
                    <p><%= article.wearable.kind.capitalize %></p>
                    <p><%= article.color.name.capitalize %></p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
          <br>
        </div>
      <% end %>
    </div>
  </div>
</div>